name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version from plugin.json
        id: version
        run: |
          echo "prop=$(jq -r '.Version' plugin.json)" >> "$GITHUB_OUTPUT"
          echo "version is $(jq -r '.Version' plugin.json)"

      - name: Package plugin
        run: |
          zip -r QuickWall.zip . -x '*.git*' '.github/*' 'README.md'
          echo "Packaged version ${{ steps.version.outputs.prop }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          files: QuickWall.zip
          tag_name: "v${{ steps.version.outputs.prop }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
